// Space → Markdown files. Output is deterministic for the same input (apart from `exported_at`).
// No API keys are ever written: provider entries carry ids only, and settings pass through stripSecrets.
import { buildPromptLayers } from "../prompt";
import { resolveSceneRefs } from "../prompt";
import { getNodeTypeDef } from "../nodeTypes";
import { buildExecutionPlan, findCycle, type WorkflowDoc } from "../workflow";
import { resolveNodeProvider, type ProviderDefaults } from "../consistency";
import type { Asset, Output, ProviderInfo, Reference, Scene, SpaceBundle } from "../types";
import {
  MARKDOWN_SCHEMA_VERSION,
  frontmatter,
  jsonBlock,
  mdEscapeCell,
  section,
  stripSecrets,
  yamlBlock,
} from "./format";

export interface ExportOptions {
  exportedAt?: string;
  providers?: ProviderInfo[];
  providerDefaults?: ProviderDefaults;
}

export type MarkdownFiles = Record<string, string>;

export function sceneFileName(n: number): string {
  return `SCENE-${String(n).padStart(2, "0")}.md`;
}

const REF_GROUPS: { title: string; types: Reference["type"][] }[] = [
  { title: "Characters", types: ["character"] },
  { title: "Products", types: ["product"] },
  { title: "Styles", types: ["style"] },
  { title: "Voices", types: ["voice"] },
  { title: "Environments", types: ["environment"] },
  { title: "Media References", types: ["image", "video", "audio"] },
];

function assetPath(assets: Asset[], id: string): string {
  const a = assets.find((x) => x.id === id);
  return a ? a.path : "MISSING";
}

function referenceYaml(r: Reference, assets: Asset[]): Record<string, unknown> {
  const settings = stripSecrets(r.settings ?? {});
  return {
    reference_id: r.code,
    type: r.type,
    name: r.name,
    revision: r.version,
    description: r.description,
    prompt: r.prompt,
    settings,
    assets: r.assetIds.map((id) => ({ asset_id: id, file: assetPath(assets, id) })),
  };
}

function sortedScenes(scenes: Scene[]): Scene[] {
  return [...scenes].sort((a, b) => a.sceneNumber - b.sceneNumber);
}

function exportProject(b: SpaceBundle, opts: ExportOptions): string {
  const { project, space, masterScript } = b;
  const fm = frontmatter({
    type: "project",
    version: MARKDOWN_SCHEMA_VERSION,
    project_id: project.id,
    project_name: project.name,
    space_id: space.id,
    space_name: space.name,
    target_platform: space.targetPlatform,
    aspect_ratio: space.aspectRatio,
    exported_at: opts.exportedAt,
    settings: stripSecrets(project.settings ?? {}),
    files: {
      master_script: "MASTER-SCRIPT.md",
      storyboard: "STORYBOARD.md",
      workflow: "WORKFLOW.md",
      prompts: "PROMPTS.md",
      assets: "ASSETS.md",
      scenes: sortedScenes(b.scenes).map((s) => `scenes/${sceneFileName(s.sceneNumber)}`),
    },
  });
  const parts = [
    fm,
    `# Project — ${project.name}\n`,
    "> Generated by AI Media Workflow. Edit the YAML frontmatter and `##` sections, then use IMPORT MARKDOWN in the app.\n> Reference IDs (MODEL_xxx, PRODUCT_xxx, ...) are stable and are used by scene files.\n",
    section("Description", project.description),
    section("Space Description", space.description),
    section("Objective", masterScript?.objective ?? ""),
    section(
      "Global Settings",
      [
        `- target_platform: ${space.targetPlatform || "-"}`,
        `- aspect_ratio: ${space.aspectRatio || "-"}`,
        `- duration: ${masterScript?.duration ? `${masterScript.duration} seconds` : "-"}`,
        `- character_id: ${masterScript?.characterId || "-"}`,
        `- product_id: ${masterScript?.productId || "-"}`,
        `- style_id: ${masterScript?.styleId || "-"}`,
        `- voice_id: ${masterScript?.voiceId || "-"}`,
        `- global_prompt: ${String(project.settings?.globalPrompt ?? "") || "-"}`,
        `- negative_prompt: ${String(project.settings?.negativePrompt ?? "") || "-"}`,
      ].join("\n"),
    ),
  ];
  for (const g of REF_GROUPS) {
    const refs = b.references.filter((r) => g.types.includes(r.type)).sort((x, y) => x.code.localeCompare(y.code));
    const body = refs.map((r) => `### ${r.code} — ${r.name}\n\n${yamlBlock(referenceYaml(r, b.assets))}`).join("\n\n");
    parts.push(section(g.title, body));
  }
  return parts.join("\n");
}

function exportMasterScript(b: SpaceBundle): string {
  const ms = b.masterScript;
  const fm = frontmatter({
    type: "master_script",
    version: MARKDOWN_SCHEMA_VERSION,
    project_id: b.project.id,
    space_id: b.space.id,
    master_script_id: ms?.id ?? "",
    revision: ms?.version ?? 0,
    title: ms?.title ?? "",
    target_platform: ms?.targetPlatform ?? b.space.targetPlatform,
    aspect_ratio: ms?.aspectRatio ?? b.space.aspectRatio,
    duration: ms?.duration ?? 0,
    character_id: ms?.characterId ?? "",
    product_id: ms?.productId ?? "",
    style_id: ms?.styleId ?? "",
    voice_id: ms?.voiceId ?? "",
    storyboard: "STORYBOARD.md",
  });
  return [
    fm,
    `# Master Script — ${ms?.title || "(untitled)"}\n`,
    section("Objective", ms?.objective ?? ""),
    section("Global Instruction", ms?.globalInstruction ?? ""),
    section("Script", ms?.scriptText ?? ""),
  ].join("\n");
}

function exportStoryboard(b: SpaceBundle): string {
  const scenes = sortedScenes(b.scenes);
  const total = scenes.reduce((a, s) => a + (s.duration || 0), 0);
  const fm = frontmatter({
    type: "storyboard",
    version: MARKDOWN_SCHEMA_VERSION,
    project_id: b.project.id,
    space_id: b.space.id,
    master_script: "MASTER-SCRIPT.md",
    scene_count: scenes.length,
    total_duration: total,
    scenes: scenes.map((s) => ({ scene_id: s.code, scene_number: s.sceneNumber, file: `scenes/${sceneFileName(s.sceneNumber)}` })),
  });
  const table = [
    "| # | scene_id | title | duration | character | product | image | video | voice | file |",
    "|---|---|---|---|---|---|---|---|---|---|",
    ...scenes.map((s) => {
      const r = resolveSceneRefs(s, b.masterScript);
      return `| ${s.sceneNumber} | ${s.code} | ${mdEscapeCell(s.title)} | ${s.duration}s | ${r.character || "-"} | ${r.product || "-"} | ${s.imageStatus} | ${s.videoStatus} | ${s.voiceStatus} | scenes/${sceneFileName(s.sceneNumber)} |`;
    }),
  ].join("\n");
  const summaries = scenes
    .map((s) => `### Scene ${String(s.sceneNumber).padStart(2, "0")} — ${s.title}\n\n${s.script.trim() || "_(no script)_"}`)
    .join("\n\n");
  return [
    fm,
    `# Storyboard — ${b.masterScript?.title || b.space.name}\n`,
    "> Summary only. The scene files in `scenes/` are authoritative and are what IMPORT MARKDOWN reads.\n",
    section("Scenes", table),
    section("Scene Summaries", summaries),
  ].join("\n");
}

function outputsFor(outputs: Output[], sceneId: string, kind: Output["kind"]): Output[] {
  return outputs.filter((o) => o.sceneId === sceneId && o.kind === kind).sort((a, b) => a.index - b.index);
}

function exportScene(b: SpaceBundle, s: Scene): string {
  const refs = resolveSceneRefs(s, b.masterScript);
  const ctx = { project: b.project, space: b.space, masterScript: b.masterScript, scene: s, references: b.references };
  const composed = (["image", "video", "voice"] as const).map((t) => buildPromptLayers(ctx, t));
  const fm = frontmatter({
    type: "scene",
    version: MARKDOWN_SCHEMA_VERSION,
    project_id: b.project.id,
    space_id: b.space.id,
    scene_id: s.code,
    scene_number: s.sceneNumber,
    revision: s.version,
    title: s.title,
    duration: s.duration,
    character_id: s.characterId,
    product_id: s.productId,
    style_id: s.styleId,
    voice_id: s.voiceId,
    resolved_character_id: refs.character,
    resolved_product_id: refs.product,
    resolved_style_id: refs.style,
    resolved_voice_id: refs.voice,
    shot_type: s.shotType,
    camera_movement: s.cameraMovement,
    location: s.location,
    lighting: s.lighting,
    expression: s.expression,
    image_provider: s.imageProvider,
    video_provider: s.videoProvider,
    voice_provider: s.voiceProvider,
    image_status: s.imageStatus,
    video_status: s.videoStatus,
    voice_status: s.voiceStatus,
    master_script: "../MASTER-SCRIPT.md",
    project: "../PROJECT.md",
  });
  const lockRules = composed[0].layers.find((l) => l.key === "continuity")?.text ?? "";
  const outLines = (["image", "video", "audio"] as const).flatMap((k) =>
    outputsFor(b.outputs, s.id, k).map((o) => `- ${k} ${o.id}${o.selected ? " (selected)" : ""}: ${o.path} — provider: ${o.provider}`),
  );
  return [
    fm,
    `# Scene ${String(s.sceneNumber).padStart(2, "0")} — ${s.title}\n`,
    "> Editable sections: Script, Action, Dialogue, Camera, Image Prompt, Video Prompt, Voice Prompt, Continuity.\n> Sections marked (generated) are rebuilt on export and ignored on import.\n",
    section("Script", s.script),
    section("Action", s.action),
    section("Dialogue", s.dialogue),
    section("Camera", s.camera),
    section("Image Prompt", s.imagePrompt),
    section("Video Prompt", s.videoPrompt),
    section("Voice Prompt", s.voicePrompt),
    section("Continuity", s.continuity),
    section("Continuity Rules (generated)", lockRules),
    section("Final Image Prompt (generated)", composed[0].final),
    section("Final Video Prompt (generated)", composed[1].final),
    section("Final Voice Instructions (generated)", composed[2].final),
    section("Outputs (generated)", outLines.join("\n")),
  ].join("\n");
}

function nodeRefSummary(b: SpaceBundle, data: Record<string, unknown>): string {
  if (data.sceneId) {
    const s = b.scenes.find((x) => x.id === data.sceneId);
    return s ? s.code : `missing:${String(data.sceneId)}`;
  }
  if (data.sceneCode) return String(data.sceneCode);
  if (data.referenceCode) return String(data.referenceCode);
  if (data.assetId) return String(data.assetId);
  if (data.templateId) return String(data.templateId);
  return "-";
}

/** Replaces internal scene ids with stable scene codes so WORKFLOW.md is portable across databases. */
export function toPortableWorkflow(doc: WorkflowDoc, scenes: Scene[]): WorkflowDoc {
  return {
    ...doc,
    nodes: doc.nodes.map((n) => {
      if (n.type !== "scene" || !n.data.sceneId) return n;
      const s = scenes.find((x) => x.id === n.data.sceneId);
      const { sceneId: _drop, ...rest } = n.data;
      return { ...n, data: { ...rest, sceneCode: s ? s.code : String(n.data.sceneId) } };
    }),
  };
}

function exportWorkflow(b: SpaceBundle, opts: ExportOptions): string {
  const doc = b.workflow;
  let order: string[] = [];
  let orderNote = "";
  const cycle = findCycle(doc);
  if (cycle) orderNote = `Cycle detected: ${cycle.join(" → ")}. Execution order unavailable.`;
  else order = buildExecutionPlan(doc).order;
  const byId = new Map(doc.nodes.map((n) => [n.id, n]));
  const label = (id: string) => {
    const n = byId.get(id);
    return n ? `${id} (${getNodeTypeDef(n.type)?.label ?? n.type})` : `${id} (MISSING)`;
  };
  const fm = frontmatter({
    type: "workflow",
    version: MARKDOWN_SCHEMA_VERSION,
    workflow_schema_version: doc.version,
    project_id: b.project.id,
    space_id: b.space.id,
    node_count: doc.nodes.length,
    edge_count: doc.edges.length,
  });
  const nodes = [
    "| node_id | type | category | refers_to |",
    "|---|---|---|---|",
    ...doc.nodes.map((n) => `| ${n.id} | ${n.type} | ${getNodeTypeDef(n.type)?.category ?? "unknown"} | ${mdEscapeCell(nodeRefSummary(b, n.data))} |`),
  ].join("\n");
  const graph = doc.edges.map((e) => `- ${label(e.source)} → ${label(e.target)}`).join("\n");
  const exec = orderNote || order.map((id, i) => `${i + 1}. ${label(id)}`).join("\n");
  const providers = opts.providers ?? [];
  const providerLines = doc.nodes
    .filter((n) => getNodeTypeDef(n.type)?.providerKind)
    .map((n) => {
      const pid = resolveNodeProvider(doc, n, b.scenes, opts.providerDefaults);
      const p = providers.find((x) => x.id === pid);
      const cfg = {
        node_id: n.id,
        type: n.type,
        provider: pid || "not configured",
        provider_status: !pid ? "not set" : p ? (p.configured ? "configured" : "not configured") : "unknown",
        model: String(n.data.model ?? "") || p?.defaultModel || "",
        aspect_ratio: n.data.aspectRatio,
        count: n.data.count,
        duration: n.data.duration,
        voice: n.data.voice,
      };
      return yamlBlock(stripSecrets(cfg));
    })
    .join("\n\n");
  const outputMap = doc.nodes
    .map((n) => {
      const outs = b.outputs.filter((o) => o.nodeId === n.id).sort((a, x) => a.index - x.index);
      if (!outs.length) return "";
      return `- ${label(n.id)}\n${outs.map((o) => `  - ${o.kind} ${o.id}${o.selected ? " (selected)" : ""}: ${o.path}`).join("\n")}`;
    })
    .filter(Boolean)
    .join("\n");
  return [
    fm,
    `# Workflow — ${b.space.name}\n`,
    section(
      "Description",
      "Node graph of this space. Every edge is a data dependency (source must finish before target runs).\nThe `Workflow JSON` block below is authoritative for IMPORT MARKDOWN. Scene nodes use `sceneCode` (matching `scene_id` in scenes/*.md).\nAPI keys are never stored here; providers are referenced by id and configured in the local `.env`.",
    ),
    section("Nodes", nodes),
    section("Dependency Graph", graph),
    section("Execution Order", exec),
    section("Provider Configuration", providerLines),
    section("Output Mapping", outputMap),
    section("Workflow JSON", jsonBlock(toPortableWorkflow(doc, b.scenes))),
  ].join("\n");
}

function exportPrompts(b: SpaceBundle): string {
  const prompts = [...b.prompts].sort((x, y) => x.category.localeCompare(y.category) || x.id.localeCompare(y.id));
  const fm = frontmatter({ type: "prompts", version: MARKDOWN_SCHEMA_VERSION, project_id: b.project.id, space_id: b.space.id, count: prompts.length });
  const cats = [...new Set(prompts.map((p) => p.category))];
  const parts = [fm, "# Prompt Library\n", "> Each template is a YAML block. Variables use `{{name}}` syntax.\n"];
  for (const c of cats) {
    const body = prompts
      .filter((p) => p.category === c)
      .map(
        (p) =>
          `### ${p.id} — ${p.name}\n\n${yamlBlock({ id: p.id, name: p.name, category: p.category, description: p.description, version: p.version, variables: p.variables, template: p.template })}`,
      )
      .join("\n\n");
    parts.push(section(c, body));
  }
  return parts.join("\n");
}

function exportAssets(b: SpaceBundle): string {
  const fm = frontmatter({ type: "assets", version: MARKDOWN_SCHEMA_VERSION, project_id: b.project.id, space_id: b.space.id, asset_count: b.assets.length, output_count: b.outputs.length, base_dir: "data" });
  const usedBy = (id: string) => b.references.filter((r) => r.assetIds.includes(id)).map((r) => r.code).join(", ") || "-";
  const table = [
    "| asset_id | kind | filename | path | used_by |",
    "|---|---|---|---|---|",
    ...[...b.assets].sort((x, y) => x.id.localeCompare(y.id)).map((a) => `| ${a.id} | ${a.kind} | ${mdEscapeCell(a.filename)} | ${a.path} | ${usedBy(a.id)} |`),
  ].join("\n");
  const outTable = [
    "| output_id | kind | scene | node_id | selected | provider | path |",
    "|---|---|---|---|---|---|---|",
    ...[...b.outputs]
      .sort((x, y) => x.createdAt.localeCompare(y.createdAt) || x.index - y.index)
      .map((o) => `| ${o.id} | ${o.kind} | ${b.scenes.find((s) => s.id === o.sceneId)?.code ?? "-"} | ${o.nodeId} | ${o.selected ? "yes" : "no"} | ${o.provider} | ${o.path} |`),
  ].join("\n");
  const data = [...b.assets]
    .sort((x, y) => x.id.localeCompare(y.id))
    .map((a) => ({ asset_id: a.id, kind: a.kind, filename: a.filename, path: a.path, mime_type: a.mimeType, size: a.size }));
  return [
    fm,
    "# Assets\n",
    "> Paths are relative to the application's `data/` directory. Files are not copied into the export.\n",
    section("Reference Assets", table),
    section("Generated Outputs", outTable),
    section("Asset Data", yamlBlock(data)),
  ].join("\n");
}

export function exportSpaceToMarkdown(bundle: SpaceBundle, opts: ExportOptions = {}): MarkdownFiles {
  const files: MarkdownFiles = {
    "PROJECT.md": exportProject(bundle, opts),
    "MASTER-SCRIPT.md": exportMasterScript(bundle),
    "STORYBOARD.md": exportStoryboard(bundle),
    "WORKFLOW.md": exportWorkflow(bundle, opts),
    "PROMPTS.md": exportPrompts(bundle),
    "ASSETS.md": exportAssets(bundle),
  };
  for (const s of sortedScenes(bundle.scenes)) files[`scenes/${sceneFileName(s.sceneNumber)}`] = exportScene(bundle, s);
  return files;
}
